name: PR

on:
  push:

jobs:
  tests:
    runs-on: [self-hosted]
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
#        env:
#          ImageOS: ubuntu18
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rspec
